version: '3'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    container_name: timescaledb
    restart: always
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - timescaledb:/var/lib/postgresql/data
      # - /data/timescaledb:/var/lib/postgresql/data

  redis-cache:
    image: redislabs/redisai:latest
    container_name: redis-cache
    volumes:
      - redis-cache:/var/lib/redis
      - redis-cache-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6371:6379
    networks:
      - redis-network

  redis-budgets:
    image: redis:latest
    container_name: redis-budgets
    command: redis-server
    volumes:
      - redis-budgets:/var/lib/redis
      - redis-budgets-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6370:6379
    networks:
      - redis-network

volumes:
  timescaledb:
  redis-cache:
  redis-cache-config:
  redis-budgets:
  redis-budgets-config:

networks:
  redis-network:
    driver: bridge